Import("env")
import gzip
import hashlib
import shutil
import subprocess
import os
from pathlib import Path
from datetime import datetime

# Write the build timestamp two ways so both firmware and filesystem carry it:
#   1. lib/WEBSERVER/build_timestamp.h  — included by webserver.cpp (same dir = no path issues)
#   2. data/buildinfo.json              — embedded in LittleFS image; JS reads FS build time
# Both files change on every build, so SCons always recompiles the affected TU.
_ts = datetime.now().strftime("%Y%m%d-%H%M%S")
_root = Path(env.subst("$PROJECT_DIR"))
(_root / "lib" / "WEBSERVER" / "build_timestamp.h").write_text(
    f'#pragma once\n#define BUILD_TIMESTAMP_STR "{_ts}"\n'
)
(_root / "data" / "buildinfo.json").write_text(
    f'{{"fsTimestamp":"{_ts}"}}\n'
)
print(f"[Build] Timestamp: {_ts}")

# ── Firmware version injection ────────────────────────────────────────────────
# Resolves to a real version string from one of three sources, in priority order:
#   1. GITHUB_REF_NAME env var (set by GitHub Actions on tag pushes, e.g. "v1.2.0")
#   2. `git describe --tags --always --dirty` (local dev with at least one tag)
#   3. Hard fallback "0.0.0-dev" (no git, no tags)
# Leading "v" is stripped so the UI's `v${version}` formatting doesn't double up.
# Header is only rewritten when the value actually changes — keeps SCons's
# incremental build cache valid across rebuilds with no version change.
def _get_firmware_version() -> str:
    ref = os.environ.get("GITHUB_REF_NAME", "").strip()
    if ref.startswith(("v", "V")) and len(ref) > 1 and ref[1].isdigit():
        return ref.lstrip("vV")
    try:
        result = subprocess.run(
            ["git", "describe", "--tags", "--always", "--dirty"],
            capture_output=True, text=True, check=True, cwd=str(_root), timeout=5,
        )
        v = result.stdout.strip()
        return v.lstrip("vV") if v else "0.0.0-dev"
    except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
        return "0.0.0-dev"

_fw_version = _get_firmware_version()
_version_header = _root / "lib" / "CONFIG" / "firmware_version.h"
_new_version_content = (
    f'#pragma once\n'
    f'// Auto-generated by scripts/extra_script.py — do not edit by hand.\n'
    f'#define FIRMWARE_VERSION "{_fw_version}"\n'
)
# Explicit UTF-8 both ways.  The header holds an em dash; with no encoding
# given, Windows wrote it in cp1252 and then a build run under PYTHONUTF8=1
# (needed so esptool v5's Unicode progress output does not crash a `pio run
# -t upload` mid-write — measured 2026-09-22, it left the app slot corrupt)
# failed here with UnicodeDecodeError.  errors="replace" lets a header from
# the old encoding be read once, compare unequal, and be rewritten cleanly.
if (not _version_header.exists()
        or _version_header.read_text(encoding="utf-8", errors="replace") != _new_version_content):
    _version_header.write_text(_new_version_content, encoding="utf-8")
    print(f"[Build] Firmware version written: {_fw_version}")
else:
    print(f"[Build] Firmware version unchanged: {_fw_version}")

# ── Web asset staging: gzip everything the browser fetches ────────────────────
#
# `data/` holds the web UI as plain, hand-editable, git-tracked source.  The
# filesystem image is built from a GENERATED staging directory instead, in which
# every compressible asset has been replaced by its `.gz` form.  `data_dir` in
# platformio.ini points at that staging directory, so BOTH image builders
# consume it:
#
#     data/  ──_stage_web_assets()─→  .pio/fsdata/  ──┬─→ pio run -t buildfs
#     (source, plain)                (generated, gz)  └─→ build_littlefs_image()
#
# Why generated rather than committing .gz files next to the sources: a
# committed .gz goes stale the moment someone edits the plain file and forgets
# to recompress, and the device then serves last week's JavaScript with no
# outward sign anything is wrong.  Regenerating every build makes that
# impossible.
#
# Why staged rather than gzipping inside build_littlefs_image(): CI does not
# call that function.  .github/workflows/release.yml runs `pio run -t buildfs`,
# PlatformIO's own packer.  Compressing in only one of the two paths would ship
# compressed assets to this bench and uncompressed ones to every published
# release — the divergence would be invisible until a user hit it.
#
# ESPAsyncWebServer's serveStatic resolves `<path>.gz` automatically and sets
# Content-Encoding (WebHandlers.cpp, _searchFile), so the four served assets
# need no firmware change.  index.html DOES need one: webserver.cpp caches it in
# a malloc'd RAM buffer rather than serving it from flash.
#
# Measured 2026-08-08 on the 7-node rig: that cache held 93,617 bytes for the
# life of the boot, against a steady-state free heap of ~79 KB.  A browser
# force-refresh re-requests every asset in parallel and costs a ~51 KB transient
# (free 79444 -> min 3144 in one second).  Starting from 79 KB that survives;
# the run that started at 60 KB hit the floor, dropped SSE, timed out all seven
# nodes and was rebooted by the heap watchdog.  Caching the 19,402-byte gzip
# instead returns ~74 KB permanently, which is what moves the floor out of
# reach.  Compressing the rest (651 KB -> 165 KB served) shortens the parallel
# connection window that produces the transient in the first place.

# Text formats only.  Anything already compressed (mp3 in /sounds, png, woff2)
# would grow, and gzipping it would also make it unreadable to any firmware path
# that opens the file directly rather than serving it.
GZIP_EXTENSIONS = {".html", ".htm", ".js", ".css", ".svg", ".json", ".xml", ".txt", ".map"}
# Below this, the ~20-byte gzip header plus LittleFS's 4 KB block granularity
# mean compression saves nothing.  Notably keeps buildinfo.json (35 bytes) plain.
GZIP_MIN_BYTES = 1024

# ── Minification ─────────────────────────────────────────────────────────────
#
# JS and CSS are minified before they are gzipped.  Measured 2026-09-22 on the
# real files: script.js 170 KB -> 63 KB gzipped, style.css 30 KB -> 9 KB.  That
# is a 63 % cut in the two files that dominate a cold page load, for nothing
# but build time.  data/ stays the readable, commented source; only the staged
# copy is minified.
#
# Uses terser and clean-css through npx, pinned to a major version so a build
# is reproducible.  Node is on every developer machine that builds this and on
# the ubuntu-latest CI runner.  If npx is missing or a minifier fails, the file
# is staged UNMINIFIED with a loud warning — a build must never break over an
# optimisation, and the firmware serves either form identically.
#
# terser's default --mangle only renames locals.  Top-level functions are kept
# by name, which index.html's inline onclick="..." handlers depend on.
MINIFY_EXTENSIONS = {".js", ".css"}
MINIFY_CMD = {
    ".js":  ["npx", "--yes", "terser@5", "{src}", "--compress", "--mangle", "-o", "{out}"],
    ".css": ["npx", "--yes", "clean-css-cli@5", "-o", "{out}", "{src}"],
}

def _minify(src, out):
    """Minify src into out.  Returns True on success, False (and warns) otherwise."""
    npx = shutil.which("npx")
    if not npx:
        print(f"[Build] WARNING: npx not found — {src.name} staged unminified")
        return False
    cmd = [npx if a == "npx" else a.format(src=str(src), out=str(out)) for a in MINIFY_CMD[src.suffix.lower()]]
    try:
        # Explicit UTF-8 with replacement: terser prints Unicode in some
        # diagnostics, and decoding those with the locale code page would
        # raise UnicodeDecodeError past the except below and abort the build
        # over an optimisation step.
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=300,
                           encoding="utf-8", errors="replace")
    except (OSError, subprocess.TimeoutExpired) as e:
        print(f"[Build] WARNING: minifier failed for {src.name} ({e}) — staged unminified")
        return False
    if r.returncode != 0 or not out.exists() or out.stat().st_size == 0:
        print(f"[Build] WARNING: minifier failed for {src.name} — staged unminified\n{r.stderr[-800:]}")
        return False
    return True

# ── Cache busting ────────────────────────────────────────────────────────────
#
# Every asset index.html references gets `?v=<8 hex chars of its staged sha1>`,
# and a <meta name="build"> carries a combined hash for scripts that
# script.js loads at runtime (loadScript() appends it).  The firmware serves
# those assets with a one-year immutable cache, so this is what makes an
# updated asset get fetched and an unchanged one never be fetched again.
# index.html itself is served no-store, so it is always current.
#
# The hash is of the STAGED (minified, gzipped) bytes, not the source, and
# index.html is regenerated on every build: a version derived from the build
# time would go stale whenever index.html was unchanged but an asset was not.
def _asset_hash(path):
    return hashlib.sha1(path.read_bytes()).hexdigest()[:8]

def _stamp_index(src_html, hashes):
    """Return index.html text with hashed asset URLs and a build meta tag.

    FAILS THE BUILD rather than staging silently when a reference cannot be
    stamped: the firmware caches these assets for a year, so an unstamped
    reference is not a cosmetic miss, it is a phone running last month's
    script.js until the cache expires.  The old 24 h TTL self-healed; this
    does not, so the check has to be here.
    """
    text = src_html.read_text(encoding="utf-8")
    for name, h in hashes.items():
        text = text.replace(f'href="{name}"', f'href="{name}?v={h}"')
        text = text.replace(f'src="{name}"',  f'src="{name}?v={h}"')
        # Any spelling this loop does not recognise — single quotes, a leading
        # slash, a stray space — would be served bare and cached for a year.
        for bare in (f"'{name}'", f'"/{name}"', f"'/{name}'", f'"{name}"'):
            if bare in text:
                raise RuntimeError(
                    f"[Build] index.html references {bare} in a form _stamp_index() "
                    f"does not stamp — write it as href=\"{name}\" / src=\"{name}\"")
    # Only the runtime-loaded scripts read this (loadScript()), so fold in the
    # .js hashes only: a CSS or logo change must not re-download smoothie.js.
    js_hashes = [h for n, h in sorted(hashes.items()) if n.endswith(".js")]
    combined = hashlib.sha1("".join(js_hashes).encode()).hexdigest()[:8]
    meta_anchor = '<meta charset="UTF-8" />'
    if meta_anchor not in text:
        raise RuntimeError(
            f'[Build] index.html has no {meta_anchor} to hang <meta name="build"> on — '
            "loadScript() would serve unversioned URLs against a one-year cache")
    text = text.replace(meta_anchor,
                        f'{meta_anchor}\n    <meta name="build" content="{combined}" />', 1)
    return text

def _stage_web_assets(env):
    """Mirror data/ into .pio/fsdata/, gzipping compressible assets.

    Lives in .pio/ (gitignored) but deliberately OUTSIDE .pio/build/: release.yml
    documents that `pio run -t buildfs` has been observed to wipe the env build
    directory, which would delete the staged files between staging and packing.

    Incremental — a file is recompressed only when its source is newer than the
    staged output, so the ~650 KB of assets are not re-gzipped on every build.
    """
    src = Path(env.subst("$PROJECT_DIR")) / "data"
    dst = Path(env.subst("$PROJECT_DIR")) / ".pio" / "fsdata"

    if not src.is_dir():
        print(f"[Build] WARNING: no data/ directory at {src} — nothing staged")
        return

    dst.mkdir(parents=True, exist_ok=True)

    staged = {}          # relative staged path -> source path, for orphan sweep
    gz_count = raw_count = 0
    total_in = total_out = 0
    hashes = {}          # asset file name -> 8-hex content hash, for index.html
    index_src = None     # staged LAST, once every asset hash is known

    for item in sorted(src.rglob("*")):
        if not item.is_file():
            continue
        rel = item.relative_to(src)
        if rel.as_posix() == "index.html":
            index_src = item
            staged["index.html.gz"] = item
            continue
        size = item.stat().st_size
        compress = item.suffix.lower() in GZIP_EXTENSIONS and size >= GZIP_MIN_BYTES
        minify   = compress and item.suffix.lower() in MINIFY_EXTENSIONS
        out = dst / (rel.with_suffix(rel.suffix + ".gz") if compress else rel)

        staged[out.relative_to(dst).as_posix()] = item
        total_in += size

        # Skip work when the staged copy is already current.  A file staged
        # unminified because the minifier failed is dated at the epoch (see
        # below) so it is retried on the next build.  A change to MINIFY_CMD
        # itself is NOT detected: delete .pio/fsdata after editing it.
        if not (out.exists() and out.stat().st_mtime >= item.stat().st_mtime):
            out.parent.mkdir(parents=True, exist_ok=True)
            if compress:
                payload = item
                minified = False
                if minify:
                    tmp = out.with_suffix(".min")        # script.js.gz -> script.js.min
                    minified = _minify(item, tmp)
                    if minified:
                        payload = tmp
                # mtime=0 keeps the output byte-identical across builds of
                # identical input, so an unchanged asset doesn't churn the
                # flashed image — and keeps its content hash, and its URL.
                with open(payload, "rb") as fin, gzip.GzipFile(out, "wb", compresslevel=9, mtime=0) as fout:
                    shutil.copyfileobj(fin, fout)
                if payload is not item:
                    payload.unlink()
                if minify and not minified:
                    # Staged unminified so the build still works — but date the
                    # output at the epoch so the freshness check above retries
                    # the minifier on the very next build instead of keeping
                    # the fallback for as long as the source is unchanged.
                    os.utime(out, (0, 0))
            else:
                shutil.copyfile(item, out)

        if compress:
            gz_count += 1
        else:
            raw_count += 1
        total_out += out.stat().st_size
        if item.parent == src and item.suffix.lower() in (".js", ".css", ".svg"):
            hashes[item.name] = _asset_hash(out)

    # index.html: always regenerated, because its content depends on every
    # other asset's hash.  gzip with mtime=0 keeps it byte-identical when
    # nothing changed, so this costs a build ~50 ms and the flash image nothing.
    if index_src is not None:
        out = dst / "index.html.gz"
        total_in += index_src.stat().st_size
        with gzip.GzipFile(out, "wb", compresslevel=9, mtime=0) as fout:
            fout.write(_stamp_index(index_src, hashes).encode("utf-8"))
        gz_count += 1
        total_out += out.stat().st_size

    # Sweep files left behind by a renamed or deleted source.  Without this a
    # stale asset would keep being flashed and served indefinitely.
    removed = 0
    for old in sorted(dst.rglob("*"), reverse=True):
        if old.is_file() and old.relative_to(dst).as_posix() not in staged:
            old.unlink()
            removed += 1
        elif old.is_dir() and not any(old.iterdir()):
            old.rmdir()

    pct = (100 * total_out // total_in) if total_in else 100
    print(f"[Build] Web assets staged -> {dst}")
    print(f"[Build]   {gz_count} gzipped, {raw_count} copied verbatim"
          + (f", {removed} stale removed" if removed else ""))
    print(f"[Build]   {total_in} -> {total_out} bytes ({pct}%)")

_stage_web_assets(env)

# ── Static RAM budget report ─────────────────────────────────────────────────
#
# Prints .dram0.data + .dram0.bss after every successful link, plus the largest
# static symbols.
#
# This is the ONLY honest way to measure static RAM.  Free-heap readings from
# the device conflate it with allocator state — a change that moves 25 KB out of
# .bss and a change that merely defers an allocation look identical at runtime,
# and only one of them actually helped.  The linker knows the truth.
#
# Context: on 2026-08-08 the device had 75,692 bytes of static DRAM, of which a
# single object (the LapTimer instance, holding the calibration wizard's 25,000
# byte scratch arrays) accounted for 25,336 — a third of all static RAM, held
# for the life of every boot, for a bench feature.  That was invisible until
# somebody looked at the ELF.
def _report_static_ram(source, target, env):
    import shutil as _sh
    elf = str(target[0])
    size_tool = env.subst("$SIZETOOL") or _sh.which("riscv32-esp-elf-size")
    if not size_tool or not os.path.exists(elf):
        return
    try:
        out = subprocess.run([size_tool, "-A", elf],
                             capture_output=True, text=True, timeout=30).stdout
    except (OSError, subprocess.TimeoutExpired):
        return

    sections = {}
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[0].startswith("."):
            try:
                sections[parts[0]] = int(parts[1])
            except ValueError:
                pass

    data = sections.get(".dram0.data", 0)
    bss  = sections.get(".dram0.bss", 0)
    total = data + bss
    if not total:
        return
    # Total DRAM on the ESP32-C6.  Everything not counted here is what the
    # allocator has left to work with at boot.
    DRAM = 327680
    # ASCII only: the PlatformIO console on Windows is cp1252 and mangles
    # non-ASCII punctuation into mojibake.
    print(f"[Build] Static RAM: {total} bytes "
          f"(.data {data} + .bss {bss}) = {100.0 * total / DRAM:.1f}% of {DRAM}")
    print(f"[Build]   Heap ceiling at boot: ~{DRAM - total} bytes")

env.AddPostAction("$BUILD_DIR/${PROGNAME}.elf", _report_static_ram)

# ── Shared helpers ────────────────────────────────────────────────────────────

ESP32_VIDS = {
    0x10C4,  # Silicon Labs CP210x
    0x1A86,  # QinHeng CH340/CH341
    0x0403,  # FTDI
    0x303A,  # Espressif native USB
    0x239A,  # Adafruit
    0x2341,  # Arduino
}

# The XIAO ESP32-C6 speaks USB natively (0x303A).  Anything reached through a
# UART bridge chip is NOT a product unit — on this bench it is the RX5808
# emulator, a WROOM-32.  Since run_esptool() hardcodes "--chip esp32c6", trying
# to flash one fails, and because do_upload_fs() returns False on ANY port
# failing, deploy_all() then aborts BEFORE the firmware step.  That leaves the
# real unit with a freshly-written filesystem and stale firmware — a mismatch
# that presents as bizarre runtime behaviour rather than an obvious flash error.
ESP32_NATIVE_USB_VID = 0x303A


def find_esp32_ports(native_only=True):
    """Ports to flash.

    native_only=True (the default for every deploy target) restricts to
    Espressif native USB, so bridge-chip boards sharing the bench — emulators,
    dev boards, anything else — are skipped rather than aborting the deploy.
    """
    try:
        import serial.tools.list_ports
        all_dev = list(serial.tools.list_ports.comports())
        if native_only:
            ports   = [p.device for p in all_dev if p.vid == ESP32_NATIVE_USB_VID]
            skipped = [p for p in all_dev
                       if p.vid in ESP32_VIDS and p.vid != ESP32_NATIVE_USB_VID]
            for p in skipped:
                print(f"  Skipping {p.device} (VID 0x{p.vid:04X}) - not a native-USB "
                      f"ESP32-C6, so not a FPVRaceOne unit.")
        else:
            ports = [p.device for p in all_dev if p.vid in ESP32_VIDS]
        if not ports:
            print(f"  No FPVRaceOne units found. All ports: "
                  f"{[p.device for p in all_dev] or 'none'}")
        return ports
    except ImportError:
        print("  ERROR: pyserial not available - cannot auto-detect ports")
        return []

def run_esptool(env, port, args):
    python = env.subst("$PYTHONEXE")
    cmd = [
        python, "-m", "esptool",
        "--chip", "esp32c6",
        "--port", port,
        "--baud", "460800",
        "--before", "default_reset",
        "--after", "hard_reset",
    ] + args
    result = subprocess.run(cmd)
    return result.returncode == 0

def print_summary(label, results):
    print(f"\n=== {label} Summary ===")
    for port, ok in results.items():
        print(f"  {port}: {'OK' if ok else 'FAILED'}")
    print()

# ── Core logic (return bool) ──────────────────────────────────────────────────

def do_connect_wifi(env):
    script = os.path.join(env.subst("$PROJECT_DIR"), "scripts", "connect_wifi.ps1")
    result = subprocess.run(
        ["powershell", "-ExecutionPolicy", "Bypass", "-File", script],
        check=False
    )
    return result.returncode == 0


FS_OFFSET    = "0x380000"  # spiffs partition in partitions_two_ota_XIAO_ESP32_C6.csv
FS_SIZE      = 0x80000     # 524288 bytes — MUST equal the spiffs partition size
                           # in partitions_two_ota_XIAO_ESP32_C6.csv.  Too large
                           # and the image written at FS_OFFSET overruns the
                           # partition (at 0xE0000 it ran past the end of a 4 MB
                           # flash entirely); too small and the device mounts a
                           # filesystem that cannot use its whole partition.
FS_BLOCK     = 4096
DISK_VERSION = (2 << 16) | 1  # LittleFS 2.1

def build_littlefs_image(env, fs_image):
    try:
        from littlefs import LittleFS
    except ImportError:
        print("  ERROR: littlefs-python not available in PlatformIO environment")
        return False

    data_dir = Path(env.subst("$PROJECT_DATA_DIR"))
    if not data_dir.is_dir():
        print(f"  ERROR: data directory not found at {data_dir}")
        return False

    print(f"  Building LittleFS image from {data_dir}...")
    block_count = FS_SIZE // FS_BLOCK
    fs = LittleFS(
        block_size=FS_BLOCK,
        block_count=block_count,
        read_size=1,
        prog_size=1,
        cache_size=FS_BLOCK,
        lookahead_size=32,
        block_cycles=500,
        name_max=64,
        disk_version=DISK_VERSION,
        mount=True,
    )

    for item in sorted(data_dir.rglob("*")):
        rel = item.relative_to(data_dir).as_posix()
        if item.is_dir():
            fs.makedirs(rel, exist_ok=True)
        else:
            if item.parent != data_dir:
                fs.makedirs(item.relative_to(data_dir).parent.as_posix(), exist_ok=True)
            with fs.open(rel, "wb") as dest:
                dest.write(item.read_bytes())

    Path(fs_image).write_bytes(fs.context.buffer)
    print(f"  Filesystem image written to {fs_image}")
    return True

def do_upload_fs(env):
    fs_image = os.path.join(env.subst("$BUILD_DIR"), "littlefs.bin")
    if not build_littlefs_image(env, fs_image):
        return False

    ports = find_esp32_ports()
    if not ports:
        return False

    print(f"\nFound {len(ports)} device(s): {', '.join(ports)}")
    print("Uploading filesystem to all...\n")

    results = {}
    for port in ports:
        print(f"── {port} ──────────────────────────────")
        results[port] = run_esptool(env, port, ["write_flash", FS_OFFSET, fs_image])

    print_summary("Filesystem Upload", results)
    return all(results.values())

def do_upload_firmware(env):
    build_dir = env.subst("$BUILD_DIR")
    fw_dir    = env.subst("$FRAMEWORK_DIR")

    bootloader = os.path.join(build_dir, "bootloader.bin")
    partitions = os.path.join(build_dir, "partitions.bin")
    firmware   = os.path.join(build_dir, "firmware.bin")
    boot_app0  = os.path.join(fw_dir, "tools", "partitions", "boot_app0.bin")

    for f, label in [(bootloader, "bootloader"), (partitions, "partitions"), (firmware, "firmware")]:
        if not os.path.exists(f):
            print(f"  ERROR: {label} not found at {f} — run 'Build' first.")
            return False

    ports = find_esp32_ports()
    if not ports:
        return False

    print(f"\nFound {len(ports)} device(s): {', '.join(ports)}")
    print("Uploading firmware to all...\n")

    flash_args = [
        "write_flash", "-z",
        "--flash_mode", "dio",
        "--flash_freq", "80m",
        "--flash_size", "detect",
        "0x0000", bootloader,
        "0x8000", partitions,
    ]
    if os.path.exists(boot_app0):
        flash_args += ["0xE000", boot_app0]
    else:
        print(f"  WARNING: boot_app0.bin not found at {boot_app0}, skipping")
    flash_args += ["0x10000", firmware]

    results = {}
    for port in ports:
        print(f"── {port} ──────────────────────────────")
        results[port] = run_esptool(env, port, flash_args)

    print_summary("Firmware Upload", results)
    return all(results.values())

# ── Individual targets ────────────────────────────────────────────────────────

def connect_wifi(source, target, env):
    do_connect_wifi(env)

env.AddCustomTarget(
    name="connect_wifi",
    dependencies=None,
    actions=connect_wifi,
    title="Connect WiFi Adapters",
    description="Connect Windows WiFi adapters to ESP32 nodes"
)

def upload_fs_all(source, target, env):
    do_upload_fs(env)

env.AddCustomTarget(
    name="upload_fs_all",
    dependencies=None,
    actions=upload_fs_all,
    title="Upload Filesystem (All Devices)",
    description="Build littlefs.bin (if needed) then flash to every connected ESP32"
)

def upload_firmware_all(source, target, env):
    do_upload_firmware(env)

env.AddCustomTarget(
    name="upload_firmware_all",
    dependencies=None,
    actions=upload_firmware_all,
    title="Upload Firmware (All Devices)",
    description="Flash firmware.bin to every connected ESP32"
)

# ── Deploy all (FS → Firmware) ────────────────────────────────────────

def deploy_all(source, target, env):
    print("\n" + "="*50)
    print("STEP 1/2: Upload Filesystem")
    print("="*50)
    if not do_upload_fs(env):
        print("\n[STOPPED] Filesystem upload failed.")
        return

    print("\n" + "="*50)
    print("STEP 2/2: Upload Firmware")
    print("="*50)
    if not do_upload_firmware(env):
        print("\n[STOPPED] Firmware upload failed.")
        return

    print("\n" + "="*50)
    print(f"Deploy complete.")
    print(f"  FW: {_ts}  (baked into firmware)")
    print(f"  FS: {_ts}  (written to buildinfo.json)")
    print("="*50 + "\n")

env.AddCustomTarget(
    name="deploy_all",
    dependencies=["$BUILD_DIR/firmware.bin"],
    actions=deploy_all,
    title="Deploy All (FS + Firmware)",
    description="Upload filesystem & upload firmware — stops on any error"
)

# ── Deploy all (FS → Firmware → WiFi) ────────────────────────────────────────

def deploy_all_wifi(source, target, env):
    print("\n" + "="*50)
    print("STEP 1/3: Upload Filesystem")
    print("="*50)
    if not do_upload_fs(env):
        print("\n[STOPPED] Filesystem upload failed.")
        return

    print("\n" + "="*50)
    print("STEP 2/3: Upload Firmware")
    print("="*50)
    if not do_upload_firmware(env):
        print("\n[STOPPED] Firmware upload failed.")
        return

    print("\n" + "="*50)
    print("STEP 3/3: Connect WiFi Adapters")
    print("="*50)
    if not do_connect_wifi(env):
        print("\n[STOPPED] WiFi connect failed.")
        return

    print("\n" + "="*50)
    print(f"Deploy complete.")
    print(f"  FW: {_ts}  (baked into firmware)")
    print(f"  FS: {_ts}  (written to buildinfo.json)")
    print("="*50 + "\n")

env.AddCustomTarget(
    name="deploy_all_wifi",
    dependencies=["$BUILD_DIR/firmware.bin"],
    actions=deploy_all_wifi,
    title="Deploy All (FS + Firmware + WiFi)",
    description="Upload filesystem, upload firmware, connect WiFi — stops on any error"
)

# ── Publish a release ─────────────────────────────────────────────────────────
#
# Two targets share the same publish_release.py script.  The script reads
# either `--prerelease` from argv or RELEASE_PRERELEASE=1 from the env to
# decide which mode it's in.  The CI workflow then keys off the presence of
# a `-` in the pushed tag to set GitHub's Pre-release flag automatically.

def _run_publish_script(env, prerelease=False):
    script = os.path.join(env.subst("$PROJECT_DIR"), "scripts", "publish_release.py")
    python = env.subst("$PYTHONEXE")
    # `-u` forces unbuffered stdout/stderr.  Without it, Python detects that
    # PIO's subprocess pipe isn't a TTY and switches to block-buffering — the
    # summary block + Proceed prompt then sit in the buffer until after input()
    # returns, so the user sees the prompt with no preceding context.
    args = [python, "-u", script]
    if prerelease:
        args.append("--prerelease")
    # Inherit stdin/stdout/stderr so the user sees prompts and can answer them.
    result = subprocess.run(args)
    if result.returncode != 0:
        # Surface the failure code so PIO marks the target as failed.
        import sys as _sys
        _sys.exit(result.returncode)

def publish_release(source, target, env):
    _run_publish_script(env, prerelease=False)

def publish_prerelease(source, target, env):
    _run_publish_script(env, prerelease=True)

env.AddCustomTarget(
    name="publish_release",
    dependencies=None,
    actions=publish_release,
    title="Publish Release (tag + push)",
    description="Tag a stable vMAJOR.MINOR.PATCH and push; CI publishes a full GitHub Release"
)

env.AddCustomTarget(
    name="publish_prerelease",
    dependencies=None,
    actions=publish_prerelease,
    title="Publish Pre-release (beta tag + push)",
    description="Tag with a -beta.N suffix and push; CI publishes with the Pre-release flag set"
)

# ── Erase + flash the latest published release onto every device ────────────
#
# Downloads the merged full-flash image + filesystem directly from the
# GitHub Releases page, FULLY ERASES each connected ESP32, then re-images
# it.  The result is byte-for-byte identical to a factory unit running that
# release — bootloader, partition table, app and filesystem all from CI.
#
# Useful for pre-release acceptance testing on hardware, or for resetting
# test devices to a known-clean baseline after local experimentation.
#
# The full erase is safe here (unlike a firmware-only flash) because
# merged.bin restores the bootloader and partition table.  Side effect: NVS
# is wiped, so devices come back with DEFAULT CONFIG — pilot names, WiFi
# credentials, calibration and node mode are all reset.  Use deploy_all
# instead if you want to keep device config.

def flash_published_release(source, target, env):
    script = os.path.join(env.subst("$PROJECT_DIR"), "scripts", "flash_published_release.py")
    python = env.subst("$PYTHONEXE")
    result = subprocess.run([python, "-u", script])
    if result.returncode != 0:
        import sys as _sys
        _sys.exit(result.returncode)

env.AddCustomTarget(
    name="flash_published_release",
    dependencies=None,
    actions=flash_published_release,
    title="Erase + Flash Published Release (All Devices)",
    description="Fully erase every connected ESP32 and re-image it from the latest GitHub Release (merged.bin + littlefs.bin) — WIPES NVS CONFIG"
)

# ── Bench test rig: RX5808 emulator ─────────────────────────────────────────
#
# Builds and uploads tools/rx5808-emulator/ to the attached WROOM-32.  Kept as
# a separate PlatformIO project so it can never be swept into a product build,
# but exposed here so it is one click from the same task list as everything
# else.
#
# Port selection is by USB vendor ID: the WROOM-32 devkit presents a CP210x /
# CH340 / FTDI bridge, while the XIAO C6 running FPVRaceOne presents Espressif
# native USB (0x303A).  The script refuses to upload to a native-USB port so
# the emulator sketch cannot land on a timer by accident.  EMULATOR_PORT
# overrides if the heuristic is wrong for your hardware.

def upload_emulator(source, target, env):
    script = os.path.join(env.subst("$PROJECT_DIR"), "scripts", "upload_emulator.py")
    python = env.subst("$PYTHONEXE")
    result = subprocess.run([python, "-u", script])
    if result.returncode != 0:
        import sys as _sys
        _sys.exit(result.returncode)

env.AddCustomTarget(
    name="upload_emulator",
    dependencies=None,
    actions=upload_emulator,
    title="Upload RX5808 Emulator (Test Rig)",
    description="Build + upload the bench RX5808 emulator to the attached WROOM-32 — refuses to target a FPVRaceOne unit"
)

# ── Bench test rig: timing harness GUI ──────────────────────────────────────
#
# Launches tools/timing-harness/gui.py — the rig that drives lap injection
# across the node fleet and reports lap-time jitter.
#
# It deliberately does NOT run under $PYTHONEXE.  PlatformIO's penv is a
# stripped virtualenv with no tkinter (verified: `import tkinter` raises
# ModuleNotFoundError there), and the harness GUI is a tkinter app, so the
# task has to find a real system interpreter.  harness.py additionally needs
# pyserial for open_port_no_reset().
#
# Set HARNESS_PYTHON to override the probe if you keep the rig's dependencies
# in a specific interpreter or virtualenv.

# _root, not __file__: SCons exec()s this script, so __file__ is undefined here.
_HARNESS_DIR = _root / "tools" / "timing-harness"


def _find_harness_python():
    """First interpreter on PATH that can actually import what the GUI needs.

    Returns (path, None) on success or (None, reason) so the caller can print
    something more useful than a traceback from a half-working interpreter.
    """
    candidates = []
    override = os.environ.get("HARNESS_PYTHON", "").strip().strip('"')
    if override:
        candidates.append(override)
    for name in ("python", "python3", "py"):
        found = shutil.which(name)
        if found and found not in candidates:
            candidates.append(found)

    if not candidates:
        return None, "no python/python3/py found on PATH"

    missing = {}
    for cand in candidates:
        try:
            probe = subprocess.run(
                [cand, "-c", "import tkinter, serial"],
                capture_output=True, text=True, timeout=30,
            )
        except (OSError, subprocess.TimeoutExpired) as e:
            missing[cand] = str(e)
            continue
        if probe.returncode == 0:
            return cand, None
        missing[cand] = (probe.stderr or "").strip().splitlines()[-1:] or ["unknown error"]

    detail = "; ".join("{}: {}".format(c, m if isinstance(m, str) else m[0])
                       for c, m in missing.items())
    return None, "no interpreter with tkinter + pyserial ({})".format(detail)


def test_rig(source, target, env):
    gui = _HARNESS_DIR / "gui.py"
    if not gui.is_file():
        print("  ERROR: harness GUI not found at {}".format(gui))
        raise SystemExit(1)

    python, why = _find_harness_python()
    if not python:
        print("  ERROR: cannot launch the test rig — {}.".format(why))
        print("  The harness needs tkinter and pyserial. Install pyserial with")
        print("    pip install pyserial")
        print("  or point HARNESS_PYTHON at an interpreter that already has both.")
        raise SystemExit(1)

    print("[Rig] Interpreter: {}".format(python))
    print("[Rig] Working dir: {}".format(_HARNESS_DIR))
    print("[Rig] Close the harness window to return to PlatformIO.\n")

    # cwd MUST be the harness directory: gui.py does a bare `from harness
    # import ...`, which only resolves when that directory is the script's
    # own location on sys.path.
    result = subprocess.run([python, "-u", str(gui)], cwd=str(_HARNESS_DIR))
    if result.returncode != 0:
        raise SystemExit(result.returncode)


env.AddCustomTarget(
    name="test_rig",
    dependencies=None,
    actions=test_rig,
    title="Run Test Rig (Timing Harness)",
    description="Launch the bench timing-harness GUI that drives lap injection across the node fleet and reports jitter"
)
